services:
  web:
    build: .
    command: >
      sh -c "
      uwsgi --ini /app/init.ini"
    ports:
      - "80:8000"

  webdev:
    build: .
    depends_on:
      - db
    profiles:
      - dev
    command: >
      sh -c "
      python manage.py collectstatic --noinput && 
      python manage.py migrate --noinput && 
      uwsgi --ini /app/init.ini"
    ports:
      - "80:8000"
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
    develop:
      watch:
        - action: sync
          path: .
          target: /app/
