services:
  web:
    build: .
    volumes:
      - .:/app
    profiles:
      - prod
    env_file:
      - .env
    command: >
      sh -c "
      # python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      uwsgi --ini /app/init.ini"
    ports:
      - "80:8000"

  webdev:
    build: .
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    profiles:
      - dev
    command: >
      sh -c "
      python manage.py makemigrations --noinput &&
      python manage.py migrate --noinput &&
      uwsgi --ini /app/init.ini"
    ports:
      - "8080:8000"
    environment:
      - DB_NAME=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_PASSWORD=admin123
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      - REDIS_HOST=redis
    develop:
      watch:
        - action: sync
          path: .
          target: /app/

  frontend:
    build:
      context: ../frontend
    profiles:
      - dev
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"

  db:
    image: postgres
    profiles:
      - dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # redis:
  #   profiles:
  #     - dev
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
