# Generated by Django 5.1.6 on 2025-02-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0002_url_custom_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
