# Generated by Django 5.1.6 on 2025-03-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0003_alter_url_short_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='custom_alias',
        ),
        migrations.RemoveField(
            model_name='url',
            name='short_url',
        ),
    ]
