# Generated by Django 5.1.6 on 2025-02-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('URLshortenerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='custom_alias',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
